#ifndef AUDIO_STREAM_H
#define AUDIO_STREAM_H

#include "xil_types.h"

#define AUDIO_SAMPLE_RATE_HZ       32000U
#define AUDIO_DURATION_SEC         10U
#define AUDIO_CHANNELS             2U
#define AUDIO_MONO_SAMPLE_COUNT    (AUDIO_SAMPLE_RATE_HZ * AUDIO_DURATION_SEC)
#define AUDIO_MONO_BYTES           (AUDIO_MONO_SAMPLE_COUNT * sizeof(s16))
#define AUDIO_STEREO_SAMPLE_COUNT  (AUDIO_MONO_SAMPLE_COUNT * AUDIO_CHANNELS)
#define AUDIO_STEREO_BYTES         (AUDIO_STEREO_SAMPLE_COUNT * sizeof(s16))

#define AUDIO_PERIOD_FRAMES        8000U
#define AUDIO_PERIOD_COUNT         8U
#define AUDIO_PERIOD_BYTES         \
    (AUDIO_PERIOD_FRAMES * AUDIO_CHANNELS * sizeof(s16))
#define AUDIO_RING_BYTES           (AUDIO_PERIOD_COUNT * AUDIO_PERIOD_BYTES)
#define AUDIO_TOTAL_PERIODS        (AUDIO_MONO_SAMPLE_COUNT / AUDIO_PERIOD_FRAMES)

/*
 * Continuous MIC capture. Audio Formatter supports at most 8 periods and
 * 50 KiB per period, which gives 3.2 seconds of stereo retention at 32 kHz.
 * This ring must outlast the blocking NPU inference (currently about 2.7 s).
 */
#define AUDIO_CAPTURE_STREAM_PERIOD_FRAMES 12800U
#define AUDIO_CAPTURE_STREAM_PERIOD_COUNT  8U
#define AUDIO_CAPTURE_STREAM_PERIOD_BYTES  \
    (AUDIO_CAPTURE_STREAM_PERIOD_FRAMES * AUDIO_CHANNELS * sizeof(s16))
#define AUDIO_CAPTURE_STREAM_RING_BYTES    \
    (AUDIO_CAPTURE_STREAM_PERIOD_COUNT * AUDIO_CAPTURE_STREAM_PERIOD_BYTES)
#define AUDIO_CAPTURE_STREAM_RETENTION_MS  3200U

#define AUDIO_MIC_HISTORY_DURATION_SEC     12U
#define AUDIO_MIC_HISTORY_SAMPLE_COUNT     \
    (AUDIO_SAMPLE_RATE_HZ * AUDIO_MIC_HISTORY_DURATION_SEC)
#define AUDIO_MIC_HISTORY_BYTES            \
    (AUDIO_MIC_HISTORY_SAMPLE_COUNT * sizeof(s16))
#define AUDIO_MIC_WINDOW_HOP_SEC            5U
#define AUDIO_MIC_WINDOW_HOP_SAMPLES        \
    (AUDIO_SAMPLE_RATE_HZ * AUDIO_MIC_WINDOW_HOP_SEC)

/* Dedicated DDR ranges, outside the NPU model/activation/Golden map. */
#define AUDIO_PLAYBACK_RING_BASE   0x05500000U
#define AUDIO_CAPTURE_RING_BASE    0x05600000U
#define AUDIO_DEMO_KNOCK_BASE      0x05700000U
#define AUDIO_DEMO_GLASS_BASE      0x05800000U
#define AUDIO_DEMO_GUNSHOT_BASE    0x05900000U
#define AUDIO_DEMO_FIRE_ALARM_BASE 0x05A00000U
#define AUDIO_MIC_HISTORY_BASE     0x05B00000U

#endif /* AUDIO_STREAM_H */
